# Generated by Django 4.1.1 on 2022-09-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesmodel',
            name='download',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
