# Generated by Django 4.1.1 on 2022-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_alter_memesmodel_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesmodel',
            name='download',
            field=models.FileField(upload_to='media/'),
        ),
    ]
